# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-01 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_mgr', '0002_auto_20170519_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='age',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='country',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='dob',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='state',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
