# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-12 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import stock_mgr.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_mgr', '0003_auto_20170601_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='thumbnail',
            field=models.FileField(default='static/assets/img/find_user.png', upload_to=stock_mgr.models.get_upload_file_name),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='dob',
            field=models.DateField(default=None),
        ),
    ]
